apiVersion: v1
kind: ConfigMap
metadata:
  name: aiops-config
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "aiops-selfheal.labels" . | indent 4 }}
data:
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  ENVIRONMENT: {{ .Values.config.ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  VERSION: {{ .Values.config.VERSION | quote }}